name: Build GCC 9.4.0

on:
  push:
    branches:
      - main

jobs:
  build-gcc:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update system packages
        run: sudo apt update && sudo apt upgrade -y

      - name: Install build dependencies
        run: sudo apt install -y build-essential bison flex libisl-dev wget gdb libmpc-dev libmpfr-dev libz3-dev

      - name: Download GCC source code
        run: wget https://ftp.gnu.org/gnu/gcc/gcc-9.4.0/gcc-9.4.0.tar.xz

      - name: Extract GCC source code
        run: tar xvf gcc-9.4.0.tar.xz

      - name: Build GCC
        run: |
          mkdir gcc_9.4.0
          cd gcc_9.4.0
          ../gcc-9.4.0/configure --prefix=$(pwd)
          make -j$(nproc)
          make install

      - name: Verify GCC build
        run: |
          cd gcc_9.4.0/bin
          ./gcc --version

      - name: Compress GCC binary folder
        run: tar cvJf gcc-9.4.0.tar.xz -C gcc_9.4.0/ bin lib

      - name: Save GCC binary folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: gcc-9.4.0.tar.xz
          path: gcc-9.4.0.tar.xz

      - name: Clean up
        run: rm -rf gcc-9.4.0* && sudo apt-get autoremove --purge -y
