name: Build GCC Libraries for x64

on:
  push:
    branches:
      - main

jobs:
  build-gcc:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update system packages
        run: sudo apt update && sudo apt upgrade -y

      - name: Install build dependencies
        run: sudo apt install -y build-essential bison flex libisl-dev wget gdb libmpc-dev libmpfr-dev libz3-dev

      - name: Download GCC source code
        run: wget https://ftp.gnu.org/gnu/gcc/gcc-9.4.0/gcc-9.4.0.tar.xz

      - name: Extract GCC source code
        run: tar xvf gcc-9.4.0.tar.xz

      - name: Build GCC libraries for x64 (C/C++ only)
        run: |
          mkdir gcc_9.4.0_build
          cd gcc_9.4.0_build
          mkdir gcc_9.4.0
          ../gcc-9.4.0/configure --prefix=$(pwd)/gcc_9.4.0 --enable-languages=c,c++ --disable-multilib
          make -j$(nproc)
          make install

      - name: Verify GCC build
        run: |
          cd gcc_9.4.0_build/gcc_9.4.0/bin
          ./gcc --version

      - name: List files in directory
        run:  |
          ls -al gcc_9.4.0_build/gcc_9.4.0

      - name: Compress GCC binary folders
        run: |
          tar cvJf gcc_9.4.0_build/gcc_9.4.0.tar.xz -C gcc_9.4.0_build/gcc_9.4.0 bin include lib lib64 libexec share

      - name: Save GCC binary folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: gcc_9.4.0.tar.xz
          path: gcc_9.4.0_build/gcc_9.4.0.tar.xz

      - name: Clean up
        run: rm -rf gcc_9.4.0_build
