name: Extractor

on:
  push:
    branches:
      - main

jobs:
  extract:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Files in Root Directory
        run: |
          echo "Contents of the root directory:"
          ls -l

      - name: List All Files in Repository
        run: |
          echo "List of all files in the repository:"
          find . -type f

      - name: Check if data.tar.xz exists
        run: |
          if [[ -f data.tar.xz ]]; then
            echo "data.tar.xz found, extracting..."
            tar -xJf data.tar.xz
          else
            echo "data.tar.xz not found"
          fi

      - name: Check if main.cpp exists
        run: |
          if [[ -f main.cpp ]]; then
            echo "main.cpp found"
          else
            echo "Error: main.cpp not found"
            exit 1
          fi

      - name: Compress main.cpp to main.tar.xz
        run: |
          tar -cJf main.tar.xz main.cpp

      - name: Check if main.tar.xz exists
        run: |
          if [[ -f main.tar.xz ]]; then
            echo "main.tar.xz created successfully"
          else
            echo "Error: main.tar.xz not created"
            exit 1
          fi
