name: Share 7z File Example
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: gh_A
          path: data/gh_A.7z

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: gh_A
          path: artifacts/
      - name: Install curl
        run: sudo apt-get install curl -y

      - name: Upload to OneDrive
        run: |
          curl -X PUT -T "artifacts/gh_A.7z" -u ${{ secrets.ONEDRIVE_USERNAME }}:${{ secrets.ONEDRIVE_PD }} "https://graph.microsoft.com/v1.0/me/drive/root:/gh_A.7z"
      
      - name: Install p7zip
        run: sudo apt-get install p7zip -y
      
      - name: Extract 7z file
        run: |
          7z x artifacts/gh_A.7z -odata/
          
      - name: Check file existence
        run: |
          if [ -f data/main.cpp ]; then
            echo "main.cpp exists"
          else
            echo "main.cpp does not exist"
            exit 1
          fi
          
  Analyze:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      actions: read
      contents: read
    strategy:
      fail-fast: false
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
         languages: cpp, python

       # Here is where you build your code
      - run: |
         g++ -o main main.cpp

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
