name: Share 7z File Example
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: gh_A
          path: gh_A.7z

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: gh_A
          path: artifacts/

      - name: Extract 7z file
        run: |
          7z x artifacts/gh_A.7z -oextracted_files

      - name: Check file existence
        run: |
          if [ -f extracted_files/main.cpp ]; then
            echo "main.cpp exists"
          else
            echo "main.cpp does not exist"
            exit 1
          fi
